import StoreCategoriesService from '../../services/store/storeCategories.service.js';

const storeCategoriesService = new StoreCategoriesService();

export default class StoreCategoriesController {
    getAllCategories = async (req, res) => {
        try {
            const { storeId, page = 1, limit = 10 } = req.query;

            const response = await storeCategoriesService.getAllCategories({ storeId, page, limit });
            return res.status(response.success ? 200 : 400).json(response);
        } catch (error) {
            console.error('‚ùå Controller - Error al obtener categor√≠as:', error);
            return res.status(500).json({
                success: false,
                message: 'Error inesperado al obtener categor√≠as',
            });
        }
    };

    createCategory = async (req, res) => {
        try {
            console.log('üü° req.files:', req.files); // üëàüèº Agrega esto
            const { name, storeId } = req.body;
            const image = req.files?.image || null;

            const response = await storeCategoriesService.createCategory({ name, storeId, image });
            return res.status(200).json(response);
        } catch (error) {
            console.error('‚ùå Controller - Error al crear categor√≠a:', error);
            const status = error.statusCode || 500;
            return res.status(status).json({
                success: false,
                message: error.message || 'Error inesperado al crear categor√≠a',
            });
        }
    };


    updateCategory = async (req, res) => {
        try {
            const { id } = req.params;
            const image = req.files?.image || null;
            const { name, storeId } = req.body;

            const response = await storeCategoriesService.updateCategory(id, { name, storeId, image });
            return res.status(response.success ? 200 : 400).json(response);
        } catch (error) {
            console.error('‚ùå Controller - Error al actualizar categor√≠a:', error);
            return res.status(500).json({
                success: false,
                message: 'Error inesperado al actualizar categor√≠a',
            });
        }
    };


    deleteCategory = async (req, res) => {
        try {
            const { id } = req.params;
            const response = await storeCategoriesService.deleteCategory(id);
            return res.status(response.success ? 200 : 400).json(response);
        } catch (error) {
            console.error('‚ùå Controller - Error al eliminar categor√≠a:', error);
            return res.status(500).json({
                success: false,
                message: 'Error inesperado al eliminar categor√≠a',
            });
        }
    };
}
